/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 과목 목록 */
        get: operations["list_subjects_api_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회차 목록 */
        get: operations["list_exams_api_exams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{exam_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회차 상세 */
        get: operations["get_exam_api_exams__exam_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{exam_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회차 문항 목록(과목 필터) */
        get: operations["list_exam_questions_api_exams__exam_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 랜덤 출제
         * @description 내용이 같은 문항(회차 간 중복)은 한 그룹으로 묶어 그룹마다 1문항만 돌려준다.
         *
         *     그룹 대표는 무작위로 고르고, 중복을 제거한 고유 그룹이 count 보다 적으면 있는 만큼만 돌려준다.
         *     목록·단건 조회는 원본 그대로라 같은 내용의 문항이 모두 나온다.
         */
        get: operations["random_questions_api_questions_random_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문항 단건 */
        get: operations["get_question_api_questions__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 채점
         * @description 고른 보기 번호를 받아 정답 여부를 돌려주고 study_attempt/study_state 에 기록한다.
         *
         *     sessionId 를 주면 그 세션에 귀속시킨다 — 없는 세션이면 404, 이미 종료된 세션이면 409 다.
         *     세션 행을 FOR UPDATE 로 잠근 채로 검사·기록하므로, 채점이 먼저 시작됐다면 /finish 가
         *     그 채점이 끝날 때까지 기다렸다가 이 채점까지 포함해 집계한다(B-01).
         *     슬롯(study_session_item)이 있는 세션은 이 경로로 기록할 수 없다(409) — 슬롯 제출
         *     `PUT /api/sessions/{sessionId}/items/{seq}/answer` 를 쓴다.
         *     종료된 세션은 기록을 받지 않으므로(제출 = 점수 확정) 계속 풀려면 새 세션을 만들어야 한다.
         */
        post: operations["answer_question_api_questions__question_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 목록
         * @description mode·cycleId 로 거를 수 있다(설계 5.4절).
         */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /**
         * 세션 시작
         * @description mode: exam_practice(회차 연습)·exam(모의고사)·random(랜덤).
         *
         *     - exam_practice·exam 은 회차의 문항 번호 순으로 슬롯(study_session_item)을 만든다.
         *       같은 모드·회차의 진행 중 세션이 있으면 409 이고, replaceActive=true 면 그 세션을
         *       abandoned 로 닫고 같은 트랜잭션에서 새로 만든다(설계 5.3절).
         *     - subject·review 는 사이클 API 로만 만들 수 있다(400).
         *     - random 은 기존대로 슬롯 없이 만든다.
         */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 세션 종료
         * @description 세션을 끝낸다(end_reason='finished'). 이미 끝난 세션을 다시 부르면 현재 상태를 그대로 돌려준다(멱등).
         *
         *     슬롯이 있는 세션은 409 다 — 연습은 마지막 문항에서 자동으로 끝나고 모의고사는 최종 제출을 쓴다.
         *     세션 행을 FOR UPDATE 로 먼저 잠가 채점과의 순서를 지킨다(B-01).
         */
        post: operations["finish_session_api_sessions__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 단건(슬롯 목록·진행)
         * @description 세션 요약 + 슬롯 목록 + 진행 위치(nextSeq). 슬롯이 없는 랜덤 세션이면 items 가 빈 목록이다.
         *
         *     진행 중인 모의고사는 isCorrect 를 null 로 가린다(제출 전 정답 비공개). 조회는 기록을 남기지 않는다.
         */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/items/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 문항(슬롯) 단건
         * @description 슬롯 문항 1개. 채점된 슬롯이면 result 에 채점 응답과 같은 형식이 붙는다.
         *
         *     채점 전 슬롯은 QuestionOut.state 를 빼서 이전 풀이의 정답 여부가 드러나지 않게 한다.
         *     조회는 원장(study_attempt)을 늘리지 않는다.
         */
        get: operations["get_session_item_api_sessions__session_id__items__seq__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/items/{seq}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 슬롯 답안 제출(연습 즉시 채점·모의고사 선택 저장)
         * @description 연습 슬롯은 즉시 채점하고, 모의고사 슬롯은 선택만 저장한다.
         *
         *     - 연습: 같은 보기 재전송은 기록 없이 저장된 결과로 200, 다른 보기는 409.
         *     - 모의고사: choiceNo=null 은 선택 해제. 정답·해설은 최종 제출 전까지 돌려주지 않는다.
         *     - 잠금 순서는 세션 → 슬롯 → 사이클이다(설계 4.6절).
         */
        put: operations["answer_session_item_api_sessions__session_id__items__seq__answer_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문항 상태 목록
         * @description 진도 목록 필터. 세 플래그 모두 `None`(미지정)이면 조건이 걸리지 않는다.
         *
         *     - `bookmarked`: true/false 로 북마크 여부를 가른다.
         *     - `wrong`: true = 한 번이라도 틀림(`wrong_count > 0`), false = 한 번도 틀린 적 없음(`wrong_count = 0`).
         *     - `unresolved`: true = 마지막 응답도 틀림, false = 마지막이 맞았거나 틀린 적 없음.
         *     - `dueOn`: 복습 예정일이 그날 이하.
         *
         *     `wrong`·`unresolved` 의 false 는 `bookmarked` 와 같은 규칙(값을 주면 조건이 된다)이며,
         *     `last_is_correct` 가 NULL 인 행(응답 이력 없이 북마크·메모만 남긴 행)도 의도한 쪽에 들어가도록
         *     부정형을 `IS NOT FALSE` 가 아니라 `(= 0 OR IS TRUE)` 로 편다.
         */
        get: operations["list_progress_questions_api_progress_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문항 상태 단건
         * @description 응답 이력이 없는 문항이면 null.
         */
        get: operations["get_progress_question_api_progress_questions__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 문항 상태 수정(북마크·메모·복습 예정일) */
        patch: operations["update_progress_question_api_progress_questions__question_id__patch"];
        trace?: never;
    };
    "/api/stats/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 과목별 정답률
         * @description 응답 기록이 없는 과목도 행이 나오고 accuracyPct 는 null.
         */
        get: operations["subject_stats_api_stats_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/wrong-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 오답 문항 */
        get: operations["wrong_questions_api_stats_wrong_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/review-due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 복습 예정 문항
         * @description 복습 예정일이 오늘(Asia/Seoul 날짜) 이하인 문항. overdueDays 0 이면 오늘.
         */
        get: operations["review_due_api_stats_review_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subject-cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사이클 목록
         * @description 과목별 이전 사이클 목록(최근 생성순). `status` 로 active·completed·abandoned 를 가른다.
         */
        get: operations["list_subject_cycles_api_subject_cycles_get"];
        put?: never;
        /**
         * 과목 사이클 시작
         * @description 과목 문항 전체를 중복 제거·셔플해 라운드 1 세션까지 만든다(설계 4.5·5.2절).
         *
         *     - 과목 문항 260개를 `content_key()` 로 묶고 그룹 대표(가장 최근 회차 = id 최대)를 모은 뒤
         *       무작위로 섞어 슬롯(seq 1..N)으로 저장한다. 목록은 만든 뒤 바뀌지 않는다.
         *     - 진행 중 사이클이 있으면 409 다. `replaceActive=true` 면 그 사이클과 그 시점의 열린 라운드를
         *       같은 트랜잭션에서 abandoned 로 닫고 새 사이클을 만든다.
         *     - 두 기기에서 동시에 시작하면 `study_cycle_active_uk` 위반이 나므로 409 로 돌려준다(설계 4.6절).
         */
        post: operations["create_subject_cycle_api_subject_cycles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subject-cycles/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 홈 요약(과목 5개 상태)
         * @description 과목 5개의 상태·고유 문항 수·진행 집계를 한 번에 돌려준다(설계 5.1절).
         *
         *     - `uniqueQuestionCount` 는 요청 시점의 문항을 `content_key()` 로 묶은 그룹 수다
         *       (과목별 176·194·194·199·181, 1,300행이라 요청마다 계산해도 부담이 없다).
         *     - `cycle` 은 진행 중 사이클이고, 없으면 마지막 완료 사이클이다(그때 `currentRound` 는 null).
         */
        get: operations["subject_cycle_overview_api_subject_cycles_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subject-cycles/{cycle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사이클 단건(라운드 목록)
         * @description 사이클 상태 + 라운드별 문항 수·답한 수·정답 수·시작·종료 시각.
         */
        get: operations["get_subject_cycle_api_subject_cycles__cycle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 태그 목록
         * @description 문항이 많은 순. q 로 이름을 걸러낸다.
         */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 헬스체크 */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChoiceAnalysisOut */
        ChoiceAnalysisOut: {
            /** No */
            no: number;
            /** Correct */
            correct: boolean;
            /** Why */
            why: string;
        };
        /** ChoiceOut */
        ChoiceOut: {
            /** No */
            no: number;
            /** Text */
            text: string;
        };
        /**
         * CycleCreate
         * @description `POST /api/subject-cycles` 본문.
         */
        CycleCreate: {
            /** Subjectcode */
            subjectCode: number;
            /**
             * Replaceactive
             * @default false
             */
            replaceActive: boolean;
        };
        /**
         * CycleOut
         * @description 사이클 단건·목록·생성 응답. `startedAt` 은 사이클 생성 시각(study_cycle.created_at)이다.
         */
        CycleOut: {
            /** Id */
            id: number;
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "abandoned";
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Endedat */
            endedAt?: string | null;
            /** Rounds */
            rounds?: components["schemas"]["RoundOut"][];
        };
        /**
         * CycleResultOut
         * @description 사이클 라운드일 때만 붙는다. 다음 라운드가 없으면 nextSessionId 가 null.
         */
        CycleResultOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Nextsessionid */
            nextSessionId?: number | null;
            /** Nextroundno */
            nextRoundNo?: number | null;
            /** Nextitemcount */
            nextItemCount?: number | null;
        };
        /** ExamDetail */
        ExamDetail: {
            /** Id */
            id: string;
            /** Year */
            year: number;
            /** Round */
            round: number;
            /** Title */
            title: string;
            /**
             * Questioncount
             * @default 0
             */
            questionCount: number;
            /**
             * Figurecount
             * @default 0
             */
            figureCount: number;
            /** Sourcepdf */
            sourcePdf?: string | null;
            /** Subjects */
            subjects?: components["schemas"]["SubjectOut"][];
        };
        /** ExamOut */
        ExamOut: {
            /** Id */
            id: string;
            /** Year */
            year: number;
            /** Round */
            round: number;
            /** Title */
            title: string;
            /**
             * Questioncount
             * @default 0
             */
            questionCount: number;
            /**
             * Figurecount
             * @default 0
             */
            figureCount: number;
        };
        /** FigureOut */
        FigureOut: {
            /**
             * Needed
             * @default false
             */
            needed: boolean;
            /** Kind */
            kind?: ("diagram" | "screen") | null;
            /** Imageurl */
            imageUrl?: string | null;
            /** Alt */
            alt?: string | null;
        };
        /** GradeRequest */
        GradeRequest: {
            /** Choiceno */
            choiceNo: number;
            /** Sessionid */
            sessionId?: number | null;
            /** Elapsedms */
            elapsedMs?: number | null;
        };
        /** GradeResult */
        GradeResult: {
            /** Questionid */
            questionId: string;
            /** Choiceno */
            choiceNo: number;
            /** Iscorrect */
            isCorrect: boolean;
            /** Answer */
            answer: number;
            /** Explanation */
            explanation: string;
            /** Keypoint */
            keyPoint?: string | null;
            /** Choicesanalysis */
            choicesAnalysis: components["schemas"]["ChoiceAnalysisOut"][];
            state: components["schemas"]["StateOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HomeCycleOut
         * @description 홈에 보여 줄 사이클: 진행 중(active)이거나, 없으면 마지막 완료(completed) 사이클.
         */
        HomeCycleOut: {
            /** Id */
            id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "abandoned";
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Endedat */
            endedAt?: string | null;
            firstRound?: components["schemas"]["RoundSummaryOut"] | null;
            currentRound?: components["schemas"]["RoundSummaryOut"] | null;
        };
        /** ProgressItem */
        ProgressItem: {
            /** Questionid */
            questionId: string;
            /**
             * Attemptcount
             * @default 0
             */
            attemptCount: number;
            /**
             * Correctcount
             * @default 0
             */
            correctCount: number;
            /**
             * Wrongcount
             * @default 0
             */
            wrongCount: number;
            /** Lastiscorrect */
            lastIsCorrect?: boolean | null;
            /** Lastchoiceno */
            lastChoiceNo?: number | null;
            /** Lastansweredat */
            lastAnsweredAt?: string | null;
            /**
             * Streak
             * @default 0
             */
            streak: number;
            /**
             * Bookmarked
             * @default false
             */
            bookmarked: boolean;
            /** Note */
            note?: string | null;
            /** Reviewdueon */
            reviewDueOn?: string | null;
            /** Updatedat */
            updatedAt?: string | null;
            /** Examid */
            examId: string;
            /** Number */
            number: number;
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName?: string | null;
            /** Stem */
            stem: string;
        };
        /**
         * QuestionOut
         * @description 조회 응답. 정답·해설·보기별 해설은 포함하지 않는다(채점 응답에서만).
         */
        QuestionOut: {
            /** Id */
            id: string;
            /** Examid */
            examId: string;
            /** Number */
            number: number;
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName?: string | null;
            /** Stem */
            stem: string;
            /** Passage */
            passage?: string | null;
            /** Passagekind */
            passageKind?: ("code" | "table" | "text") | null;
            /** Difficulty */
            difficulty?: number | null;
            /** Choices */
            choices?: components["schemas"]["ChoiceOut"][];
            figure?: components["schemas"]["FigureOut"];
            /** Tags */
            tags?: string[];
            state?: components["schemas"]["StateOut"] | null;
        };
        /** QuestionPage */
        QuestionPage: {
            /** Items */
            items: components["schemas"]["QuestionOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ReviewDueOut */
        ReviewDueOut: {
            /** Questionid */
            questionId: string;
            /** Examid */
            examId: string;
            /** Number */
            number: number;
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName: string;
            /** Stem */
            stem: string;
            /**
             * Reviewdueon
             * Format: date
             */
            reviewDueOn: string;
            /** Overduedays */
            overdueDays: number;
            /** Lastiscorrect */
            lastIsCorrect?: boolean | null;
            /** Wrongcount */
            wrongCount: number;
            /** Note */
            note?: string | null;
        };
        /**
         * RoundOut
         * @description 사이클의 라운드 1회(= 세션). 집계는 슬롯(study_session_item) 기준이다.
         *
         *     `itemCount` 는 라운드에 담긴 문항 수, `answered` 는 답한 슬롯 수, `correct` 는 맞힌 수다.
         */
        RoundOut: {
            /** Sessionid */
            sessionId: number;
            /** Roundno */
            roundNo: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "exam" | "exam_practice" | "subject" | "random" | "review";
            /**
             * Itemcount
             * @default 0
             */
            itemCount: number;
            /**
             * Answered
             * @default 0
             */
            answered: number;
            /**
             * Correct
             * @default 0
             */
            correct: number;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Finishedat */
            finishedAt?: string | null;
            /** Endreason */
            endReason?: string | null;
        };
        /**
         * RoundResultOut
         * @description 이 제출로 라운드(세션)가 끝났을 때만 붙는다. roundNo 는 회차 연습·모의고사면 null.
         */
        RoundResultOut: {
            /** Roundno */
            roundNo?: number | null;
            /** Itemcount */
            itemCount: number;
            /** Correct */
            correct: number;
            /** Wrong */
            wrong: number;
        };
        /**
         * RoundSummaryOut
         * @description 홈 요약의 라운드 집계. 라운드가 없으면 null 이고, 있으면 세 값이 항상 채워진다.
         */
        RoundSummaryOut: {
            /** Sessionid */
            sessionId?: number | null;
            /** Roundno */
            roundNo?: number | null;
            /**
             * Itemcount
             * @default 0
             */
            itemCount: number;
            /**
             * Answered
             * @default 0
             */
            answered: number;
            /**
             * Correct
             * @default 0
             */
            correct: number;
        };
        /** SessionCreate */
        SessionCreate: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "exam" | "exam_practice" | "subject" | "random" | "review";
            /** Examid */
            examId?: string | null;
            /** Subjectcode */
            subjectCode?: number | null;
            /**
             * Replaceactive
             * @default false
             */
            replaceActive: boolean;
        };
        /**
         * SessionDetailOut
         * @description 세션 단건 조회. 슬롯 목록과 진행 위치(nextSeq)를 함께 준다.
         */
        SessionDetailOut: {
            /** Id */
            id: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "exam" | "exam_practice" | "subject" | "random" | "review";
            /** Examid */
            examId?: string | null;
            /** Subjectcode */
            subjectCode?: number | null;
            /** Cycleid */
            cycleId?: number | null;
            /** Roundno */
            roundNo?: number | null;
            /** Endreason */
            endReason?: string | null;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Finishedat */
            finishedAt?: string | null;
            /**
             * Answered
             * @default 0
             */
            answered: number;
            /**
             * Correct
             * @default 0
             */
            correct: number;
            /**
             * Itemcount
             * @default 0
             */
            itemCount: number;
            /**
             * Answeredcount
             * @default 0
             */
            answeredCount: number;
            /** Nextseq */
            nextSeq?: number | null;
            /** Items */
            items?: components["schemas"]["SessionItemOut"][];
        };
        /**
         * SessionItemDetail
         * @description 슬롯 문항 단건: QuestionOut + 슬롯 상태 + result.
         *
         *     채점 전에는 state 를 null 로 빼서 이전 풀이의 정답 여부가 드러나지 않게 한다.
         */
        SessionItemDetail: {
            /** Id */
            id: string;
            /** Examid */
            examId: string;
            /** Number */
            number: number;
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName?: string | null;
            /** Stem */
            stem: string;
            /** Passage */
            passage?: string | null;
            /** Passagekind */
            passageKind?: ("code" | "table" | "text") | null;
            /** Difficulty */
            difficulty?: number | null;
            /** Choices */
            choices?: components["schemas"]["ChoiceOut"][];
            figure?: components["schemas"]["FigureOut"];
            /** Tags */
            tags?: string[];
            state?: components["schemas"]["StateOut"] | null;
            /** Seq */
            seq: number;
            /** Choiceno */
            choiceNo?: number | null;
            /** Iscorrect */
            isCorrect?: boolean | null;
            /** Answeredat */
            answeredAt?: string | null;
            result?: components["schemas"]["GradeResult"] | null;
        };
        /**
         * SessionItemOut
         * @description 세션 슬롯 1개(요약). 진행 중인 모의고사는 isCorrect 를 null 로 가린다.
         */
        SessionItemOut: {
            /** Seq */
            seq: number;
            /** Questionid */
            questionId: string;
            /** Choiceno */
            choiceNo?: number | null;
            /** Iscorrect */
            isCorrect?: boolean | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "exam" | "exam_practice" | "subject" | "random" | "review";
            /** Examid */
            examId?: string | null;
            /** Subjectcode */
            subjectCode?: number | null;
            /** Cycleid */
            cycleId?: number | null;
            /** Roundno */
            roundNo?: number | null;
            /** Endreason */
            endReason?: string | null;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Finishedat */
            finishedAt?: string | null;
            /**
             * Answered
             * @default 0
             */
            answered: number;
            /**
             * Correct
             * @default 0
             */
            correct: number;
        };
        /**
         * SessionProgressOut
         * @description 제출 응답에 붙는 세션 진행 정보. nextSeq 는 다음에 풀 슬롯(없으면 null).
         */
        SessionProgressOut: {
            /** Id */
            id: number;
            /**
             * Itemcount
             * @default 0
             */
            itemCount: number;
            /**
             * Answeredcount
             * @default 0
             */
            answeredCount: number;
            /** Nextseq */
            nextSeq?: number | null;
            /**
             * Finished
             * @default false
             */
            finished: boolean;
        };
        /**
         * SlotAnswerRequest
         * @description 슬롯 제출. 모의고사에서 choiceNo=null 은 선택 해제다(연습에서는 필수).
         */
        SlotAnswerRequest: {
            /** Choiceno */
            choiceNo?: number | null;
            /** Elapsedms */
            elapsedMs?: number | null;
        };
        /**
         * SlotGradeResult
         * @description 연습 슬롯 제출 응답: 채점 결과 + 세션 진행 + 라운드·사이클 상태.
         */
        SlotGradeResult: {
            /** Questionid */
            questionId: string;
            /** Choiceno */
            choiceNo: number;
            /** Iscorrect */
            isCorrect: boolean;
            /** Answer */
            answer: number;
            /** Explanation */
            explanation: string;
            /** Keypoint */
            keyPoint?: string | null;
            /** Choicesanalysis */
            choicesAnalysis: components["schemas"]["ChoiceAnalysisOut"][];
            state: components["schemas"]["StateOut"];
            session: components["schemas"]["SessionProgressOut"];
            roundResult?: components["schemas"]["RoundResultOut"] | null;
            cycle?: components["schemas"]["CycleResultOut"] | null;
        };
        /**
         * SlotSaveOut
         * @description 모의고사 선택 저장 응답. 정답·해설은 최종 제출 전까지 돌려주지 않는다.
         */
        SlotSaveOut: {
            /** Seq */
            seq: number;
            /** Choiceno */
            choiceNo?: number | null;
            /** Answeredat */
            answeredAt?: string | null;
        };
        /** StateOut */
        StateOut: {
            /** Questionid */
            questionId: string;
            /**
             * Attemptcount
             * @default 0
             */
            attemptCount: number;
            /**
             * Correctcount
             * @default 0
             */
            correctCount: number;
            /**
             * Wrongcount
             * @default 0
             */
            wrongCount: number;
            /** Lastiscorrect */
            lastIsCorrect?: boolean | null;
            /** Lastchoiceno */
            lastChoiceNo?: number | null;
            /** Lastansweredat */
            lastAnsweredAt?: string | null;
            /**
             * Streak
             * @default 0
             */
            streak: number;
            /**
             * Bookmarked
             * @default false
             */
            bookmarked: boolean;
            /** Note */
            note?: string | null;
            /** Reviewdueon */
            reviewDueOn?: string | null;
            /** Updatedat */
            updatedAt?: string | null;
        };
        /** StateUpdate */
        StateUpdate: {
            /** Bookmarked */
            bookmarked?: boolean | null;
            /** Note */
            note?: string | null;
            /** Reviewdueon */
            reviewDueOn?: string | null;
        };
        /** SubjectOut */
        SubjectOut: {
            /** Code */
            code: number;
            /** Name */
            name: string;
            /** Fromno */
            fromNo: number;
            /** Tono */
            toNo: number;
            /** Questioncount */
            questionCount?: number | null;
        };
        /**
         * SubjectOverviewOut
         * @description 과목 1개의 홈 요약(`GET /api/subject-cycles/overview` 한 행).
         */
        SubjectOverviewOut: {
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName: string;
            /** Uniquequestioncount */
            uniqueQuestionCount: number;
            /**
             * Status
             * @enum {string}
             */
            status: "not_started" | "first_pass" | "reviewing" | "completed";
            cycle?: components["schemas"]["HomeCycleOut"] | null;
        };
        /** SubjectStatsOut */
        SubjectStatsOut: {
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName: string;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Wrong */
            wrong: number;
            /** Questionstotal */
            questionsTotal: number;
            /** Questionsseen */
            questionsSeen: number;
            /** Accuracypct */
            accuracyPct?: number | null;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Questioncount
             * @default 0
             */
            questionCount: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WrongQuestionOut */
        WrongQuestionOut: {
            /** Questionid */
            questionId: string;
            /** Examid */
            examId: string;
            /** Number */
            number: number;
            /** Subjectcode */
            subjectCode: number;
            /** Subjectname */
            subjectName: string;
            /** Stem */
            stem: string;
            /** Attemptcount */
            attemptCount: number;
            /** Wrongcount */
            wrongCount: number;
            /** Lastchoiceno */
            lastChoiceNo?: number | null;
            /** Lastiscorrect */
            lastIsCorrect?: boolean | null;
            /** Lastansweredat */
            lastAnsweredAt?: string | null;
            /**
             * Bookmarked
             * @default false
             */
            bookmarked: boolean;
            /** Note */
            note?: string | null;
            /** Reviewdueon */
            reviewDueOn?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_subjects_api_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"][];
                };
            };
        };
    };
    list_exams_api_exams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamOut"][];
                };
            };
        };
    };
    get_exam_api_exams__exam_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exam_questions_api_exams__exam_id__questions_get: {
        parameters: {
            query?: {
                subjectCode?: number | null;
                difficulty?: number | null;
                tag?: string[] | null;
                figureOnly?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                exam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    random_questions_api_questions_random_get: {
        parameters: {
            query?: {
                examId?: string | null;
                subjectCode?: number | null;
                tag?: string[] | null;
                figureOnly?: boolean;
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_question_api_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_questions__question_id__answer_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Exam-Token"?: string | null;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                mode?: ("exam" | "exam_practice" | "subject" | "random" | "review") | null;
                cycleId?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Exam-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_session_api_sessions__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Exam-Token"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_item_api_sessions__session_id__items__seq__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_session_item_api_sessions__session_id__items__seq__answer_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Exam-Token"?: string | null;
            };
            path: {
                session_id: number;
                seq: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotGradeResult"] | components["schemas"]["SlotSaveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_progress_questions_api_progress_questions_get: {
        parameters: {
            query?: {
                bookmarked?: boolean | null;
                wrong?: boolean | null;
                unresolved?: boolean | null;
                dueOn?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_question_api_progress_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_progress_question_api_progress_questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Exam-Token"?: string | null;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subject_stats_api_stats_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectStatsOut"][];
                };
            };
        };
    };
    wrong_questions_api_stats_wrong_questions_get: {
        parameters: {
            query?: {
                unresolvedOnly?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WrongQuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_due_api_stats_review_due_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDueOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subject_cycles_api_subject_cycles_get: {
        parameters: {
            query?: {
                subjectCode?: number | null;
                status?: ("active" | "completed" | "abandoned") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subject_cycle_api_subject_cycles_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Exam-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CycleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subject_cycle_overview_api_subject_cycles_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOverviewOut"][];
                };
            };
        };
    };
    get_subject_cycle_api_subject_cycles__cycle_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycle_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: {
                /** @description 이름 부분일치(대소문자 무시) */
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
